### ISSUE TITLE
ModuleNotFoundError: No module named 'ffmpy'

### ISSUE THREAD

**Issue by esrichen** [Ch00k/ffmpy#67] opened 2023-07-06 07:35 UTC
an error occurred while run 'pip install ffmpy':
Collecting ffmpy
  Using cached ffmpy-0.3.0.tar.gz (4.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\LENOVO\AppData\Local\Temp\pip-install-qdjjte43\ffmpy_b931f8fcb2204140a8f27606b5cdbd63\setup.py", line 4, in <module>
          from ffmpy import __version__
      ModuleNotFoundError: No module named 'ffmpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Ch00k** [comment] 2023-07-17 08:37
This is a duplicate of #65. For some reason this seems to be happening only on Windows though.

**Closed by Ch00k** 2023-07-17 08:37 UTC
